import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'tushar',
      email: 'admin@example.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: true,
      isSeller: true,
    },
    {
      name: 'raj',
      email: 'user@example.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: false,
      isSeller: true,
    },
    {
      name: 'prajakta',
      email: 'prajakta@example.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: false,
      isSeller: false,
    },
    {
      name: 'pooja',
      email: 'pooja@example.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: false,
      isSeller: false,
    },
    {
      name: 'Sardar',
      email: 'Sardar@example.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: false,
      isSeller: false,
    },
    {
      name: 'onkar',
      email: 'onkar@example.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: false,
      isSeller: false,
    },
  ],
  products: [
    {
      name: 'Vivo Y21',
      slug: 'Vivo Y21',
      category: 'Electronics',
      per: 'Unit',
      image: '/images/vivo_Y21.jpg',
      price: 13490,
      countInStock: 10,
      brand: 'Vivo',
      rating: 4.5,
      numReviews: 10,
      description:
        '13MP+2MP Rear Camera | 8MP Selfie Camera 16.55cm (6.51) HD+ Display with 1600 x 720 pixels resolution.Memory & SIM: 4GB RAM | 64GB internal memory | Dual SIM (nano+nano) dual-standby (4G).Funtouch OS 11.1 operating system based on Android 11 with Mediatek Helio P35 Octa core processor.18W fast charging with 5000mAh battery (Type-C).',
    },
    {
      name: 'OnePlus 10R',
      slug: 'OnePlus 10R',
      category: 'Electronics',
      per: 'Unit',
      image: '/images/oneplus_10R.jpg',
      price: 32490,
      countInStock: 10,
      brand: 'OnePlus',
      rating: 4.5,
      numReviews: 10,
      description:
        'Camera: 50MP Main Camera with Sony IMX766 and 2MP Macro Camera with Dual LED Flash; 16MP Front (Selfie) Camera with Sony IMX471 Camera Features: Nightscape2.0, Super Macro, UltraShot HDR, Smart Scene Recognition, Portrait mode, Pro mode, Panorama, Tilt-shift mode, Focus Peaking, Filters, Video Nightscape, Video HDR, Video Portrait Timelapse, Hyperlapse Mode Display: 6.7 Inches; 120 Hz IRIS Display; Resolution: 2400 X 1080 pixels 394 ppi; Aspect Ratio: 20:9 Display Features: Hyper Touch Mode, Reading Mode, Night Mode, Eye Comfort Mode, Auto brightness Operating System: OxygenOS based on Android 12, Processor: MTK D8100 Max Battery & Charging: 5000 mAh with 80W SuperVOOC In-Display Fingerprint Sensor',
    },
    {
      name: 'Noise Pulse 2',
      slug: 'Noise Pulse 2',
      category: 'Electronics',
      per: 'Unit',
      image: '/images/noicePulse2.jpg',
      price: 1999,
      countInStock: 10,
      brand: 'Noise',
      rating: 4.5,
      numReviews: 10,
      description:
        'Massive 1.85" display: See everyday data clearly under the brightest sun on the 1.85 TFT LCD that sports 500 nits of brightness and the highest screen-to-body ratio. BT calling: Talk directly to your loved ones from your wrist; manage calls, access your favourite contacts and dial from the dial pad. Tru Sync: Now connect with the world smart way, thanks to Tru Sync technology that ensures faster and stable connection and low power consumption. Smart DND: Take a break when you want to and get uninterrupted sleep time. Noise Health Suite: Get started on your fitness journey with a whole range of wellness features in Noise Health Suite and 100 sports modes to support you. NoiseFit app: Manage your day-to-day life better with the NoiseFit app at your disposal. 150+ cloud-based watch faces: A new day calls for a new face, choose from over 150+ cloud-based watch faces and don a new look every day.',
    },
    {
      name: 'ZEBRONICS',
      slug: 'Zeb Evolve (Blue)',
      category: 'Electronics',
      per: 'Unit',
      image: '/images/zebronics.jpg',
      price: 599,
      countInStock: 20,
      brand: 'ZEBRONICS',
      rating: 4.5,
      numReviews: 10,
      description:
        'In Ear Wireless Neckband Earphone Rapid Charge Function: 2 hours usage in 10 minutes charge Up to 17H Playback at 50% Volume Seamless Connectivity with BT5.0 Magnetic Earpiece, Charging time - 1h, Talk time - 12H, Standby time - 40H Dual Pairing Feature Call Function with Media/Volume Controls',
    },
    {
      name: '15s-ey2000au',
      slug: '15s-ey2000au',
      category: 'Electronics',
      per: 'Unit',
      image: '/images/HP_15s-Ryzen.jpg',
      price: 45599,
      countInStock: 20,
      brand: 'HP',
      rating: 4.5,
      numReviews: 10,
      description:
        'Do Check Partner offer section for Exciting offers from HP.Processor: AMD Ryzen 3 5300U (up to 3.8 GHz max boost clock(2i),4 MB L3 cache, 4 cores, 8 threads)| Memory & Storage: 8 GB DDR4-3200 SDRAM (1 x 8 GB), Upto 16 GB DDR4-3200 MHz RAM (2 x 8 GB)| Storage: 256 GB PCIe NVMe M.2 SSD Display & Graphics: (15.6") diagonal FHD, micro-edge, anti-glare, 250 nits, 141 ppi, 45%NTSC |Graphics: AMD Radeon Graphics Operating System & Pre-installed Software: Pre-loaded Windows 11 Home 64 Single Language| Microsoft Office 2019 & Office 365|McAfee LiveSafe (30 days free trial as default) Ports: 1 SuperSpeed USB Type-C 5Gbps signaling rate, 2 SuperSpeed USB Type-A 5Gbps signaling rate,1 Headphone/microphone Combo,1 AC Smart pin, 1 HDMI 1.4b',
    },
    {
      name: 'Think Like a Monk',
      slug: 'think-like-a-monk',
      category: 'Book',
      per: 'unit',
      image: '/images/b1.png',
      price: 250,
      countInStock: 10,
      brand: 'Thorsons',
      rating: 4.5,
      numReviews: 10,
      description:
        '“Think Like a Monk” reveals how to overcome negative thoughts and habits, and access the calm and purpose that lie within all of us. The lessons monks learn are profound but often abstract. Shetty transforms them into advice and exercises we can all apply to reduce stress, improve focus, improve relationships, identify our hidden abilities, increase self-discipline and give the gifts we find in ourselves to the world. Shetty proves that everyone can – and should – think like a monk.',
    },
    {
      name: 'Think Straight',
      slug: 'think-straight',
      category: 'Book',
      per: 'unit',
      image: '/images/b2.png',
      price: 139,
      countInStock: 20,
      brand: 'Penguin',
      rating: 3.5,
      numReviews: 15,
      description:
        "' THINK STRAIGHT reveals the recipe for taking control of your mind so you can improve your life, career, relationships, business. I wrote this little book in a way that you can read it more than once. And I hope that this book serves as an anchor to you--especially during trying times. The mind is the most powerful tool on earth. Change the way you think. And you'll change your life.'",
    },
    {
      name: 'The Psychology of Money',
      slug: 'the-psychology-of-money',
      category: 'Book',
      per: 'unit',
      image: '/images/b3.png',
      price: 210,
      countInStock: 15,
      brand: 'Jaico Publishing House',
      rating: 4.1,
      numReviews: 5,
      description:
        ' Timeless lessons on wealth, greed, and happiness doing well with money isn?t necessarily about what you know. It?s about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically considered to involve a lot of mathematical calculations, where data and formulae tell us exactly what to do. ',
    },
    {
      name: 'Sparx',
      slug: 'Sparx mens Sf0567g Slipper',
      category: 'FootWear',
      per: 'Unit',
      image: '/images/Sparx.jpg',
      price: 524,
      countInStock: 20,
      brand: 'Sparx',
      rating: 4.5,
      numReviews: 10,
      description:
        'Flaunt with these stylish and unique black red flip flops as per the latest fashion trend from the house of Sparx. Super comfortable flip flops with Rubber as upper material and Rubber as sole material.',
    },
    {
      name: 'puma',
      slug: 'Puma mens Prime Idp Iron Gate-sunflower-puma Black Outdoor Sandals',
      category: 'FootWear',
      per: 'Unit',
      image: '/images/puma.jpg',
      price: 1200,
      countInStock: 50,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Flaunt the latest & coolest styles from Puma.',
    },
    {
      name: 'Nike',
      slug: "Nike Women's WMNS Revolution 4 Black Shoes",
      category: 'FootWear',
      per: 'Unit',
      image: '/images/Nike.jpg',
      price: 3200,
      countInStock: 40,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        "More support around the heel pairs with the foot-hugging feel of Flyknit. The futuristic sole completes the package, for a shoe that's as ready for your quick run as it is for an elevated look.",
    },
    {
      name: 'BRK',
      slug: "B.R.K. Men's Denim Casual Shoes",
      category: 'FootWear',
      per: 'Unit',
      image: '/images/BRK.jpg',
      price: 1200,
      countInStock: 50,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description:
        'stop stop stop!! Are you looking for branded shoe so BRK trade mark company brought a very stylish ,comfortable , valuable floatable walkable and With an excellent design, this pair of shoes is an elegant choice for all fashion-savvy men.Complete your smart outfit matching these shoes with a slim shirt and a pair of trousers.The sole promises great traction on the surface, thus promising ultimate comfort, whereas the perforated design is for added appeal. Put On An Unruffled And Spontaneous Look Wearing This Pair Of Modish Shoes Designed To Pull Off A Magnificent Persona. Smart And Stylish, These Casual Shoes For Men, Are A Must Have In Your Footwear Closet. Team This Trendy Pair With Jeans And A T-Shirt As You Get Ready For An Outing. Buy This Online From Amazon.Com To Complete Your Look.',
    },
    {
      name: 'Denill',
      slug: "Denill Women's Pink Fashion Sandal",
      category: 'FootWear',
      per: 'Unit',
      image: '/images/puma.jpg',
      price: 499,
      countInStock: 50,
      brand: 'Denill',
      rating: 4.5,
      numReviews: 10,
      description:
        'Elevate your style with this comfortable pair of fashion sandal from the house of Denill brand. Featuring a contemporary refined design with exceptional comfort, this pair is perfect to give your quintessential dressing an upgrade.',
    },
    {
      name: 'The Alchemist',
      slug: 'the-alchemist',
      category: 'Book',
      per: 'unit',
      image: '/images/b4.png',
      price: 232,
      countInStock: 15,
      brand: 'Harper',
      rating: 4.5,
      numReviews: 20,
      description:
        "'Paulo Coelho's enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and inspiring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried in the Pyramids. '",
    },
    {
      name: 'kigai: The Japanese secret to a long and happy life',
      slug: 'ikigai',
      category: 'Book',
      per: 'unit',
      image: '/images/b5.png',
      price: 307,
      countInStock: 10,
      brand: 'Random House UK',
      rating: 4.5,
      numReviews: 20,
      description:
        "'THE INTERNATIONAL BESTSELLER We all have an ikigai. It's the Japanese word for ‘a reason to live’ or ‘a reason to jump out of bed in the morning’. It’s the place where your needs, desires, ambitions, and satisfaction meet. A place of balance. Small wonder that finding your ikigai is closely linked to living longer. Finding your ikigai is easier than you might think. This book will help you work out what your own ikigai really is, and equip you to change your life. '",
    },
    {
      // _id: '1',
      name: 'nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirt',
      per: 'unit',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'hight quality shirt',
    },
    {
      // _id: '2',
      name: 'adidas fit shirt',
      slug: 'adidas-fit-shirt',
      category: 'shirt',
      per: 'unit',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'hight quality shirt',
    },
    {
      // _id: '3',
      name: 'nike slim pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      per: 'unit',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'hight quality Product',
    },
    {
      // _id: '4',
      name: 'Adidas fit pant',
      slug: 'Adidas-fit-pant',
      category: 'Pants',
      per: 'unit',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 14,
      description: 'hight quality Product',
    },

    {
      name: 'Tata salt',
      slug: 'Tata salt',
      category: 'salt',
      per: 'KG',
      image: '/images/tata.jpg',
      price: 20,
      countInStock: 15,
      brand: 'Tata',
      rating: 4.5,
      numReviews: 100,
      description: 'salt with iodine',
    },

    {
      name: 'Parle Biscuit',
      slug: 'Parle Biscuit',
      category: 'biscuit',
      per: 'unit',
      image: '/images/parle.jpg',
      price: 5,
      countInStock: 50,
      brand: 'Parle',
      rating: 5,
      numReviews: 35,
      description: 'Sugar free biscuits',
    },

    {
      name: 'Dettol soap',
      slug: 'Dettol soap',
      category: 'soap',
      per: 'unit',
      image: '/images/dettol.webp',
      price: 12,
      countInStock: 26,
      brand: 'Dettol',
      rating: 4.8,
      numReviews: 18,
      description: 'Kills 99.99% germs',
    },

    {
      name: 'Patanjali soyabean oil',
      slug: 'Patanjali soyabean oil',
      category: 'edible oil',
      per: 'liter',
      image: '/images/soyaoil.jpg',
      price: 56,
      countInStock: 40,
      brand: 'Patanjali',
      rating: 3.2,
      numReviews: 4,
      description: 'Process free oil',
    },

    {
      name: 'Fortune Sunflower oil',
      slug: 'Fortune Sunflower oil',
      category: 'edible oil',
      per: 'liter',
      image: '/images/fortune.webp',
      price: 72,
      countInStock: 23,
      brand: 'Fortunr',
      rating: 4.1,
      numReviews: 22,
      description: 'Refined oil with Vit A,B,E and cholestrol free',
    },

    {
      name: 'Oreo biscuit',
      slug: 'Oreo biscuit',
      category: 'biscuit',
      per: 'unit',
      image: '/images/123.jpg',
      price: 20,
      countInStock: 40,
      brand: 'Fortunr',
      rating: 4.9,
      numReviews: 42,
      description: 'Black and White cream biscuit',
    },
    {
      name: 'Dhoodh biscuit',
      slug: 'Dhoodh biscuit',
      category: 'biscuit',
      per: 'unit',
      image: '/images/patanjali.jpg',
      price: 10,
      countInStock: 56,
      brand: 'Patanjali',
      rating: 3.4,
      numReviews: 62,
      description: 'Natural glutn free rice biscuit',
    },

    {
      name: 'Neem kanti saop',
      slug: 'Neem kanti saop',
      category: 'saop',
      per: 'unit',
      image: '/images/neem.jpg',
      price: 10,
      countInStock: 16,
      brand: 'Patanjali',
      rating: 4.2,
      numReviews: 37,
      description: 'Antibacterial natural neem saop',
    },
  ],
};

export default data;
